"""add_password_hash_nullable_google_id

Revision ID: 9df8b0aad10e
Revises: c2bb4ce928ff
Create Date: 2026-04-03 14:35:22.526878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df8b0aad10e'
down_revision: Union[str, None] = 'c2bb4ce928ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.Text(), nullable=True))
    op.alter_column('users', 'google_id',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'google_id',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
