"""add_password_hash_nullable_google_id

Revision ID: 9df8b0aad10e
Revises: c2bb4ce928ff
Create Date: 2026-04-03 14:35:22.526878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df8b0aad10e'
down_revision: Union[str, None] = 'c2bb4ce928ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.Text(), nullable=True))
        batch_op.alter_column('google_id',
                   existing_type=sa.TEXT(),
                   nullable=True)
        batch_op.create_unique_constraint('uq_users_email', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')
        batch_op.alter_column('google_id',
                   existing_type=sa.TEXT(),
                   nullable=False)
        batch_op.drop_column('password_hash')
    # ### end Alembic commands ###
